Repository massalabs/station, pull requests merged in 2022-11, with the labels that each got.

#244 Allow cors
  .gitignore
  api/swagger/server/restapi/configure_thyra_server.go
  go.mod
  go.sum
Labels: tech

#234 Update installation.md
  INSTALLATION.md
Labels: action:merge

#246 improve quit gui
  int/api/server.go
Labels: action:merge, pr:fix

#245 Polish readme
  README.md
Labels: action:merge

#257 adds port to localhost rpc url
  int/api/server.go
Labels: enhancement, action:merge

#294 golangci-lint how to
  README.md
Labels: action:merge

#306 Load Wallet needs to be doable only once with same private key.
  int/api/html/front/errors.js
  int/api/wallet/errors.go
  int/api/wallet/import.go
  pkg/gui/wallet_loader.go
  pkg/wallet/wallet.go
Labels: action:merge
