Repository massalabs/station, pull requests merged in 2022-10, with the labels that each got.

#161 159 format file info link missing
  pkg/front/website/html.go
  resource/html/front/website.html
Labels: action:merge, pr:fix

#163 160 add missing label about max file size
  pkg/front/website/html.go
  resource/html/front/website.html
Labels: action:merge, pr:fix

#165 Resolve Vocabulary issues, clear DNS, and solve website storer issue
  pkg/front/wallet/html.go
  pkg/onchain/dns/dns.go
  pkg/onchain/website/uploader.go
  pkg/sc/websiteStorer.go
  pkg/wallet/wallet.go
  resource/html/front/wallet.html
  resource/sc/websiteStorer.wasm
Labels: action:merge

#164 137 back send operation endpoint creation
  .golangci.yml
  .prettierrc.yaml
  api/swagger/server/restapi/embedded_spec.go
  api/swagger/server/restapi/operations/cmd_execute_function.go
  api/swagger/server/restapi/resource/swagger.yml
  cmd/thyra-server/main.go
  int/api/cmd/errors.go
  int/api/cmd/execute_function.go
Labels: action:merge

#176 172 macos create a basic installation script
  scripts/macos_install.sh
Labels: action:merge

#158 136 - Add GUI for password prompt
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  .gitignore
  README.md
  api/swagger/server/restapi/operations/cmd_execute_function_parameters.go
  api/swagger/server/restapi/operations/mgmt_wallet_create_parameters.go
  api/swagger/server/restapi/operations/mgmt_wallet_import_parameters.go
  api/swagger/server/restapi/server.go
  cmd/thyra-server/main.go
  go.mod
  go.sum
  gon_amd64.json
  gon_arm64.json
  int/api/html/front/errors.js
  int/api/html/front/website.html
  int/api/html/front/website.js
  int/api/server.go
  int/api/websites/webcreator.go
  int/c/main.go
  pkg/gui/password.go
Labels: action:merge, feature, CI

#194 191 link sign trasaction endpoint to prompt password
  README.md
  int/api/cmd/execute_function.go
  int/api/html/front/website.js
  int/api/server.go
  int/api/websites/webcreator.go
  pkg/gui/password.go
Labels: action:merge

#187 fixes missing directory for macos installation script
  scripts/macos_install.sh
Labels: action:merge

#197 196-remove-website-size-upload-limit
  int/api/html/front/website.html
  int/api/html/front/website.js
  int/api/websites/webcreator.go
Labels: action:merge

#195 169 regression event manager not showing the chunk upload correctly
  int/api/events.go
  int/api/html/front/website.js
Labels: action:merge

#198 168 regression import from button not showing text
  int/api/html/front/website.css
  int/api/html/front/website.js
Labels: action:merge

#212 change check folder exists
  scripts/macos_install.sh
Labels: action:merge

#206 203 bug mime type error on browser after running thyra
  api/swagger/server/restapi/doc.go
  api/swagger/server/restapi/embedded_spec.go
  api/swagger/server/restapi/operations/thyra_server_api.go
  api/swagger/server/restapi/resource/swagger.yml
  int/api/html/front/registry.html
  int/api/html/front/wallet.html
  int/api/html/front/website.html
  int/api/utils.go
Labels: action:merge

#205 202 create a parameter to change the limit upload size of thyra web on chain
  int/api/html/front/website.html
  int/api/html/front/website.js
  int/api/thyra.go
  int/api/utils.go
  int/api/websites/webcreator.go
Labels: feature

#217 214 separate created wallets from thyra binary directory
  int/api/wallet/create.go
  int/api/wallet/import.go
  pkg/wallet/wallet.go
Labels: action:merge
