Repository massalabs/station, pull requests merged in 2023-07, with the labels that each got.

#937 web: add absolute relative path
  web/massastation/src/components/SidePanels/Upload/Upload.tsx
  web/massastation/src/const/const.ts
  web/massastation/src/const/index.ts
  web/massastation/src/pages/Base/Base.tsx
  web/massastation/src/pages/Error.tsx
  web/massastation/src/pages/Index/Index.tsx
  web/massastation/src/pages/Search/DomainModelItem/DomainModelItem.tsx
  web/massastation/src/pages/Search/Loading.tsx
  web/massastation/src/pages/Search/Search.tsx
  web/massastation/src/pages/Store/Install.tsx
  web/massastation/src/pages/Store/StationSection/StationPlugin.tsx
  web/massastation/src/pages/Store/StationSection/StationSection.tsx
  web/massastation/src/pages/Store/Store.tsx
  web/massastation/src/pages/Store/StoreSection/StorePlugin.tsx
  web/massastation/src/pages/Store/StoreSection/StoreSection.tsx
  web/massastation/src/utils/massaConstants.ts
  web/massastation/src/utils/utils.ts
  web/massastation/tsconfig.json
  web/massastation/vite.config.ts
  web/shared/consts/index.ts
  web/shared/index.ts
  web/shared/interfaces/index.ts
Labels: Frontend

#951 Remove Scroll Behavior From Home Page
  web/massastation/src/pages/Index/Index.tsx
Labels: action:merge

#968 Add Logo On Windows
  .github/workflows/api.yml
  installer/windows/assets/logo.ico
  installer/windows/build_installer.py
Labels: action:merge

#942 Fix Store Calls
  web/massastation/src/pages/Store/StationSection/StationPlugin.tsx
  web/massastation/src/pages/Store/StationSection/StationSection.tsx
  web/massastation/src/pages/Store/StoreSection/StorePlugin.tsx
  web/massastation/src/pages/Store/StoreSection/StoreSection.tsx
Labels: action:merge

#1002 update go in CI 1.20.6
  .github/actions/install/action.yml
  .github/workflows/lint.yml
  gen.go
  pkg/node/sendoperation/executesc/executesc.go
  pkg/node/sendoperation/sendoperation.go
  pkg/wallet/wallet.go
Labels: action:merge

#978 976 centralize cross package configuration in intconf package
  int/configuration/ca.go
  int/configuration/ca_darwin_test.go
  int/configuration/ca_linux_test.go
  int/configuration/ca_test.go
  int/configuration/ca_windows_test.go
  int/configuration/configuration.go
  int/configuration/configuration_test.go
  int/configuration/configuration_unix_test.go
  int/configuration/configuration_windows_test.go
  pkg/certificate/authority.go
  pkg/certificate/certificate.go
Labels: action:merge

#1053 do not delete wallet files
  pkg/plugin/manager.go
  pkg/plugin/manager_test.go
Labels: P1
