Repository massalabs/station, pull requests merged in 2023-09, with the labels that each got.

#1121 fix delete a plugin other than the wallet
  api/test/robot_tests/plugin_manager/plugin_manager.robot
  pkg/plugin/manager.go
Labels: P2

#1157 Remove useless configDir from struct RegistryHandler
  cmd/massastation/main.go
  int/api/server.go
  int/api/websites/all.go
Labels: tech, P3

#1178 clean code uninstall plugin
  pkg/plugin/manager.go
  pkg/plugin/manager_test.go
Labels: action:merge, tech

#1185 update PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/release.yml
Labels: ignore-for-changelog

#1190 mv PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ignore-for-changelog

#1192 update wallet version in tests
  api/test/robot_tests/cmd/keywords.resource
Labels: ignore-for-changelog

#1188 edit-installation-docs
  INSTALLATION.md
Labels: documentation

#1198 update ui-kit (autoclose dropdown)
  web/massastation/package-lock.json
Labels: bugfix

#1199 Clean Plugin Version Display
  web/massastation/package-lock.json
  web/massastation/src/pages/Store/StationSection/StationPlugin.tsx
  web/massastation/src/pages/Store/StoreSection/StorePlugin.tsx
Labels: ignore-for-changelog
