Repository massalabs/station, pull requests merged in 2023-06, with the labels that each got.

#739 Update INSTALLATION.md
  INSTALLATION.md
Labels: action:merge

#774 Connect plugins
  web/massastation/package-lock.json
  web/massastation/src/mirage/server.js
  web/massastation/src/pages/store/MyPlugin.tsx
  web/massastation/src/pages/store/MyStation.tsx
  web/massastation/src/pages/store/Store.tsx
  web/massastation/src/utils/massaConstants.ts
Labels: action:merge

#738 734 update contributing
  CONTRIBUTING.md
Labels: action:merge

#804 fix web app routing
  CONTRIBUTING.md
  api/middleware.go
  api/test/robot_tests/plugin_store/plugin_store.robot
  int/api/thyra.go
  int/systray/systray.go
  web/massastation/.env.dev
  web/massastation/.env.prod
  web/massastation/README.md
  web/massastation/package.json
  web/massastation/src/const/env/env.ts
  web/massastation/src/main.tsx
Labels: pr:fix

#819 download plugin from url in the side pannel
  web/massastation/src/i18n/en_US.json
  web/massastation/src/mirage/server.js
  web/massastation/src/pages/Store/Install.tsx
  web/massastation/src/pages/Store/StationSection/StationSection.tsx
  web/massastation/src/pages/Store/Store.tsx
  web/massastation/src/pages/Store/StoreSection/StoreSection.tsx
Labels: action:merge

#836 web: open website on click
  web/massastation/src/pages/Search/DomainModelItem/DomainModelItem.tsx
Labels: Frontend

#875 add connection / install wallet button
  web/massastation/src/layouts/LayoutStation/LayoutStation.tsx
Labels: Frontend

#884 web: update account store
  web/massastation/src/components/SidePanels/Upload/Upload.tsx
  web/massastation/src/layouts/LayoutStation/LayoutStation.tsx
  web/massastation/src/store/accountStore.ts
Labels: Frontend

#887 web: move DropDown into sidePanel
  web/massastation/package-lock.json
  web/massastation/src/components/SidePanels/Upload/Upload.tsx
  web/massastation/src/mirage/server.js
Labels: Frontend

#898 web: migrate mirage from JS to TS
  web/massastation/src/main.tsx
  web/massastation/src/mirage/config.ts
  web/massastation/src/mirage/factories/account.ts
  web/massastation/src/mirage/factories/domain.ts
  web/massastation/src/mirage/factories/index.ts
  web/massastation/src/mirage/factories/network.ts
  web/massastation/src/mirage/factories/plugin.ts
  web/massastation/src/mirage/factories/store.ts
  web/massastation/src/mirage/handlers/account.ts
  web/massastation/src/mirage/handlers/domain.ts
  web/massastation/src/mirage/handlers/index.ts
  web/massastation/src/mirage/handlers/network.ts
  web/massastation/src/mirage/handlers/plugin.ts
  web/massastation/src/mirage/handlers/store.ts
  web/massastation/src/mirage/index.ts
  web/massastation/src/mirage/models/index.ts
  web/massastation/src/mirage/server.js
  web/massastation/src/mirage/types.ts
  web/massastation/tsconfig.json
  web/shared/interfaces/IPlugin.ts
Labels: Frontend

#927 station: add favicon
  web/massastation/index.html
  web/massastation/public/.gitkeep
  web/massastation/public/favicon.ico
Labels: Frontend

#929 Fix debian postrm script during upgrade
  installer/deb/scripts/postrm
Labels: action:merge, P1
